language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t mouhebrahmi/dockerwithreact -f Dockerfile.dev .

script:
  - docker run -e CI=true mouhebrahmi/dockerwithreact npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: dockerwithreact
  env: "Dockerwithreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-225078125041"
  bucket_path: "dockerwithreact"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
